FROM node:20 as build

WORKDIR /app
COPY src/fe/package.json src/fe/package-lock.json ./
RUN npm install

COPY src/fe/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
